from research_agent.prompts.execution import (
    EXECUTION_INSTRUCTIONS,
    EXECUTION_ROLE,
)
from research_agent.prompts.financial_research import (
    COMPANY_FINANCIAL_RESEARCH_INSTRUCTIONS,
    COMPANY_FINANCIAL_RESEARCH_ROLE,
    FUNDAMENTAL_ANALYSIS_INSTRUCTIONS,
    FUNDAMENTAL_ANALYSIS_ROLE,
    MACRO_ECONOMIC_INSTRUCTIONS,
    MACRO_ECONOMIC_ROLE,
    RISK_MANAGEMENT_INSTRUCTIONS,
    RISK_MANAGEMENT_ROLE,
    TEAM_INSTRUCTIONS,
    TECHNICAL_ANALYSIS_INSTRUCTIONS,
    TECHNICAL_ANALYSIS_ROLE,
    TERM_SHEET_INSTRUCTIONS,
    TERM_SHEET_ROLE,
)

__all__ = [
    "COMPANY_FINANCIAL_RESEARCH_INSTRUCTIONS",
    "COMPANY_FINANCIAL_RESEARCH_ROLE",
    "EXECUTION_INSTRUCTIONS",
    "EXECUTION_ROLE",
    "FUNDAMENTAL_ANALYSIS_INSTRUCTIONS",
    "FUNDAMENTAL_ANALYSIS_ROLE",
    "MACRO_ECONOMIC_INSTRUCTIONS",
    "MACRO_ECONOMIC_ROLE",
    "RISK_MANAGEMENT_INSTRUCTIONS",
    "RISK_MANAGEMENT_ROLE",
    "TECHNICAL_ANALYSIS_INSTRUCTIONS",
    "TECHNICAL_ANALYSIS_ROLE",
    "TERM_SHEET_INSTRUCTIONS",
    "TERM_SHEET_ROLE",
    "TEAM_INSTRUCTIONS",
]
